use crate::clients::llm_client;
use crate::models::{
    developer_response::DeveloperResponse, reviewer_response::ReviewerResponse,
    teamlead_response::TeamLeaderResponse,
};
use crate::services::{file_system, git_local, github};
use std::fs;

pub async fn run_factory() -> Result<(), Box<dyn std::error::Error>> {
    println!("Checking GitHub for open issues...");
    let issues = github::fetch_open_issues().await?;

    if issues.is_empty() {
        println!("No open issues found. Factory is resting.");
        return Ok(());
    }

    let target_issue = &issues[0]; // Process the first open issue
    let issue_body = target_issue.body.clone().unwrap_or_default();
    let issue_text = format!("Title: {} Body: {}", target_issue.title, issue_body);

    println!(
        "Processing Issue #{}: {}",
        target_issue.number, target_issue.title
    );

    // 1. TEAM LEADER PHASE
    let team_lead_prompt = fs::read_to_string("config/team_lead.md")?;
    println!("Team Leader is thinking...");
    let lead_raw = llm_client::ask(&team_lead_prompt, &issue_text).await?;

    let lead_res: TeamLeaderResponse =
        serde_json::from_str(&lead_raw).expect("Failed to parse Team Leader JSON");

    println!("Agent Assigned: {}", lead_res.assigned_agent);
    println!("Architecture Plan: {}", lead_res.architectural_plan);

    // 2. DEVELOPER PHASE (Dynamically load the correct agent prompt)
    let dev_prompt_path = format!("config/{}.md", lead_res.assigned_agent);
    let dev_prompt = fs::read_to_string(&dev_prompt_path).unwrap_or_else(|_| {
        println!("Agent config not found, falling back to backend_dev");
        fs::read_to_string("config/backend_dev.md").unwrap()
    });

    // We send both the issue and the Leader's plan to the Dev
    let dev_input = format!(
        "Issue:\n{}\n\nArchitectural Plan:\n{}",
        issue_text, lead_res.architectural_plan
    );

    println!("{} is writing code...", lead_res.assigned_agent);
    let dev_raw = llm_client::ask(&dev_prompt, &dev_input).await?;

    let dev_res: DeveloperResponse =
        serde_json::from_str(&dev_raw).expect("Failed to parse Developer JSON");

    println!("Dev Thought: {}", dev_res.thought_process);

    // 3. APPLY CHANGES & GIT OPERATIONS
    git_local::create_branch(&dev_res.branch_name)?;
    file_system::apply_modifications(dev_res.files_to_modify)?;

    let commit_msg = format!(
        "feat: Resolve issue #{} - Auto-generated by AI",
        target_issue.number
    );
    let _ = git_local::commit_changes(&commit_msg);

    // 4. REVIEWER PHASE
    println!("Reviewer is analyzing the code...");
    let reviewer_prompt = fs::read_to_string("config/reviewer.md")?;

    // Get the git diff to show the reviewer what changed
    let git_diff = git_local::get_diff_against_main().unwrap_or_default();
    let reviewer_input = format!("Here is the git diff for the new feature: {}", git_diff);

    let rev_raw = llm_client::ask(&reviewer_prompt, &reviewer_input).await?;
    let rev_res: ReviewerResponse =
        serde_json::from_str(&rev_raw).expect("Failed to parse Reviewer JSON");

    if rev_res.is_approved {
        println!("REVIEW APPROVED: Code is clean and production-ready!");

        git_local::push_to_remote(&dev_res.branch_name)?;

        println!("Opening Pull Request on GitHub...");
        let pr_title = format!("Resolve Issue #{} - Auto AI PR", target_issue.number);
        let pr_body = format!(
            "**Automated PR by AI Software Factory**  **Agent Thought Process:** {}  **Reviewer Notes:** Approved automatically.",
            dev_res.thought_process
        );

        match github::create_pull_request(&pr_title, &pr_body, &dev_res.branch_name, "main").await {
            Ok(url) => println!("🎉 BOOM! Pull Request opened successfully: {}", url),
            Err(e) => println!("⚠️ Failed to open PR: {}", e),
        }
    } else {
        println!("❌ REVIEW REJECTED: Changes required.");
        if let Some(feedback) = rev_res.feedback_thread {
            println!("Feedback: {}", feedback);
        }
    }

    println!("Workflow completed for Issue #{}!", target_issue.number);
    Ok(())
}
